### ISSUE TITLE
Apple Stamp

### ISSUE THREAD

**Issue by jluo98** [net-art-and-cultures/net-artware#19]
The user should be able to click the "apple stamp" option in the brush menu, after which point they should see images of apple logo appear onto the canvas when they click and drag their mouse

**Comment by jluo98** [comment]
@nbriz I don't have access to assign myself or change labels.

**Comment by nbriz** [comment]
@Steve-luo oh strange, for some reason u weren't on the list? even though u had been added during class? not sure what happened, but u should have access now (let me know if it didn't work though)
